export interface Tag {
	label: string;
	color: string;
}

export enum TagName {
	Donations = 'Donations',
	Social = 'Social',
	Sports = 'Sports',
	SelfCare = 'SelfCare',
	Shopping = 'Shopping',
	Volunteer = 'Volunteer',
	Animals = 'Animals',
	Reading = 'Reading',
	Literature = 'Literature',
	Cooking = 'Cooking',
	Events = 'Events',
	Wellness = 'Wellness',
	Work = 'Work',
	Productivity = 'Productivity',
	Fitness = 'Fitness',
	Environment = 'Environment',
	Sustainability = 'Sustainability',
	Organization = 'Organization',
	Home = 'Home',
	Learning = 'Learning',
	Entertainment = 'Entertainment',
	Goals = 'Goals',
	Creativity = 'Creativity',
	Hobbies = 'Hobbies',
	Fun = 'Fun',
	Languages = 'Languages',
	Community = 'Community',
	Fundraising = 'Fundraising',
	Education = 'Education',
	History = 'History',
	Family = 'Family',
	Heritage = 'Heritage',
	Food = 'Food',
	Travel = 'Travel',
	Adventure = 'Adventure',
	Art = 'Art',
	Culture = 'Culture',
	Finance = 'Finance',
	Planning = 'Planning',
	Reflection = 'Reflection',
	Mindfulness = 'Mindfulness',
	Skills = 'Skills',
	Networking = 'Networking',
	DIY = 'DIY',
	Inspiration = 'Inspiration',
	Exploration = 'Exploration',
	Writing = 'Writing',
	Nature = 'Nature',
	Music = 'Music',
	Career = 'Career',
	Dining = 'Dining',
	Friendship = 'Friendship',
	Leisure = 'Leisure',
	Memories = 'Memories',
	Photography = 'Photography',
	Health = 'Health',
	Media = 'Media',
	Tech = 'Tech',
	Relaxation = 'Relaxation',
	Gardening = 'Gardening',
	Growth = 'Growth',
	Outdoor = 'Outdoor',
	Holidays = 'Holidays',
	Preparation = 'Preparation',
	Business = 'Business',
	Innovation = 'Innovation'
}

export const tags: Record<TagName, Tag> = Object.freeze({
	Writing: { label: 'Writing', color: 'accent2' },
	Nature: { label: 'Nature', color: 'accent' },
	Music: { label: 'Music', color: 'secondary' },
	Career: { label: 'Career', color: 'tertiary' },
	Dining: { label: 'Dining', color: 'accent' },
	Friendship: { label: 'Friendship', color: 'accent2' },
	Leisure: { label: 'Leisure', color: 'secondary' },
	Memories: { label: 'Memories', color: 'tertiary' },
	Photography: { label: 'Photography', color: 'accent' },
	Health: { label: 'Health', color: 'accent2' },
	Media: { label: 'Media', color: 'secondary' },
	Tech: { label: 'Tech', color: 'tertiary' },
	Relaxation: { label: 'Relaxation', color: 'accent' },
	Gardening: { label: 'Gardening', color: 'accent2' },
	Growth: { label: 'Growth', color: 'secondary' },
	Outdoor: { label: 'Outdoor', color: 'tertiary' },
	Holidays: { label: 'Holidays', color: 'accent' },
	Preparation: { label: 'Preparation', color: 'accent2' },
	Business: { label: 'Business', color: 'secondary' },
	Innovation: { label: 'Innovation', color: 'tertiary' },
	Shopping: { label: 'Shopping', color: 'accent' },
	Volunteer: { label: 'Volunteer', color: 'accent2' },
	Animals: { label: 'Animals', color: 'secondary' },
	Reading: { label: 'Reading', color: 'tertiary' },
	Literature: { label: 'Literature', color: 'accent' },
	Cooking: { label: 'Cooking', color: 'accent2' },
	Events: { label: 'Events', color: 'secondary' },
	Wellness: { label: 'Wellness', color: 'tertiary' },
	Work: { label: 'Work', color: 'accent' },
	Productivity: { label: 'Productivity', color: 'accent2' },
	Fitness: { label: 'Fitness', color: 'secondary' },
	Environment: { label: 'Environment', color: 'tertiary' },
	Sustainability: { label: 'Sustainability', color: 'accent' },
	Organization: { label: 'Organization', color: 'accent2' },
	Home: { label: 'Home', color: 'secondary' },
	Learning: { label: 'Learning', color: 'tertiary' },
	Entertainment: { label: 'Entertainment', color: 'accent' },
	Goals: { label: 'Goals', color: 'accent2' },
	Creativity: { label: 'Creativity', color: 'secondary' },
	Hobbies: { label: 'Hobbies', color: 'tertiary' },
	Fun: { label: 'Fun', color: 'accent' },
	Languages: { label: 'Languages', color: 'accent2' },
	Community: { label: 'Community', color: 'secondary' },
	Fundraising: { label: 'Fundraising', color: 'tertiary' },
	Education: { label: 'Education', color: 'accent' },
	History: { label: 'History', color: 'accent2' },
	Family: { label: 'Family', color: 'secondary' },
	Heritage: { label: 'Heritage', color: 'tertiary' },
	Food: { label: 'Food', color: 'accent' },
	Travel: { label: 'Travel', color: 'accent2' },
	Adventure: { label: 'Adventure', color: 'secondary' },
	Art: { label: 'Art', color: 'tertiary' },
	Culture: { label: 'Culture', color: 'accent' },
	Finance: { label: 'Finance', color: 'accent2' },
	Planning: { label: 'Planning', color: 'secondary' },
	Reflection: { label: 'Reflection', color: 'tertiary' },
	Mindfulness: { label: 'Mindfulness', color: 'accent' },
	Skills: { label: 'Skills', color: 'accent2' },
	Networking: { label: 'Networking', color: 'secondary' },
	DIY: { label: 'DIY', color: 'tertiary' },
	Inspiration: { label: 'Inspiration', color: 'accent' },
	Exploration: { label: 'Exploration', color: 'accent2' },
	Donations: { label: 'Donations', color: 'accent' },
	Social: { label: 'Social', color: 'accent2' },
	Sports: { label: 'Sports', color: 'secondary' },
	SelfCare: { label: 'SelfCare', color: 'tertiary' },
});
