name: Build & Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master', 'main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment:
      name: GH_Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install
        env:
          NODE_ENV: Production
        run: |
          npm ci;
      - name: Dump PWD
        run: pwd
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/spa
